export const browserCoreExamples = [
  "aipro browser status",
  "aipro browser start",
  "aipro browser stop",
  "aipro browser tabs",
  "aipro browser open https://example.com",
  "aipro browser focus abcd1234",
  "aipro browser close abcd1234",
  "aipro browser screenshot",
  "aipro browser screenshot --full-page",
  "aipro browser screenshot --ref 12",
  "aipro browser snapshot",
  "aipro browser snapshot --format aria --limit 200",
  "aipro browser snapshot --efficient",
  "aipro browser snapshot --labels",
];

export const browserActionExamples = [
  "aipro browser navigate https://example.com",
  "aipro browser resize 1280 720",
  "aipro browser click 12 --double",
  'aipro browser type 23 "hello" --submit',
  "aipro browser press Enter",
  "aipro browser hover 44",
  "aipro browser drag 10 11",
  "aipro browser select 9 OptionA OptionB",
  "aipro browser upload /tmp/file.pdf",
  'aipro browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "aipro browser dialog --accept",
  'aipro browser wait --text "Done"',
  "aipro browser evaluate --fn '(el) => el.textContent' --ref 7",
  "aipro browser console --level error",
  "aipro browser pdf",
];
